import { motion } from 'framer-motion';
import { FaCalendar, FaUser, FaClock, FaArrowLeft } from 'react-icons/fa';
import { Link, useParams } from 'react-router-dom';

// Helper function to convert slug back to title
function slugToTitle(slug) {
  return slug
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

// Sample article data - this would typically come from an API or database
const articles = {
  'ai-governance-in-african-democracies': {
    title: 'AI Governance in African Democracies',
    author: 'Dr. Amara Okonkwo',
    date: 'December 15, 2024',
    readTime: '8 min read',
    image:
      'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: 'Artificial Intelligence has emerged as a transformative force across the globe, and Africa stands at a critical juncture in determining how these technologies will shape democratic governance on the continent.',
      },
      { type: 'heading', text: 'Understanding the Landscape' },
      {
        type: 'paragraph',
        text: 'African democracies face unique challenges in the digital age. From election integrity to civic participation, AI technologies offer both opportunities and risks that must be carefully navigated with African contexts in mind.',
      },
      { type: 'heading', text: 'Opportunities for Democratic Strengthening' },
      {
        type: 'paragraph',
        text: 'AI can enhance electoral processes through improved voter registration systems, fraud detection, and result verification. Machine learning algorithms can help identify patterns of electoral manipulation while preserving voter privacy and autonomy.',
      },
      {
        type: 'paragraph',
        text: 'Furthermore, AI-powered platforms can facilitate greater civic engagement by making government services more accessible, enabling real-time feedback mechanisms, and supporting multilingual communication across diverse communities.',
      },
      { type: 'heading', text: 'Addressing the Challenges' },
      {
        type: 'paragraph',
        text: 'However, the deployment of AI in democratic processes must contend with issues of algorithmic bias, data privacy, and the digital divide. Without careful implementation, these technologies risk reinforcing existing inequalities and creating new forms of exclusion.',
      },
      { type: 'heading', text: 'The Path Forward' },
      {
        type: 'paragraph',
        text: 'The Uzawi Initiative advocates for a human-centered approach to AI deployment in democratic contexts. This means prioritizing transparency, accountability, and meaningful participation from civil society in the design and implementation of AI systems.',
      },
      {
        type: 'paragraph',
        text: 'African nations must develop their own AI governance frameworks that reflect local values, priorities, and democratic principles rather than simply adopting models from other regions.',
      },
    ],
  },
  'digital-sovereignty-a-pan-african-perspective': {
    title: 'Digital Sovereignty: Why Africa Must Control Its Data',
    author: 'Kwame Mensah',
    date: 'December 10, 2024',
    readTime: '6 min read',
    image:
      'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: 'Data has become the most valuable resource of the 21st century, yet African nations have limited control over the vast amounts of data generated by their citizens and economies.',
      },
      { type: 'heading', text: 'The Current State of Data Control' },
      {
        type: 'paragraph',
        text: "Most of Africa's digital infrastructure is owned and operated by foreign corporations. Cloud services, social media platforms, and digital payment systems store African data on servers located outside the continent, subject to foreign laws and corporate interests.",
      },
      { type: 'heading', text: 'Economic Implications' },
      {
        type: 'paragraph',
        text: 'This data extraction represents a form of digital colonialism where African data fuels the AI models and digital economies of other regions while providing limited economic benefit to the continent itself.',
      },
      { type: 'heading', text: 'Building Data Sovereignty' },
      {
        type: 'paragraph',
        text: 'True digital sovereignty requires investment in local data infrastructure, development of regional data governance frameworks, and policies that ensure data generated in Africa benefits African people and economies.',
      },
    ],
  },
  'social-media-and-democracy-lessons-from-recent-african-elections': {
    title: 'Social Media and Democracy: Lessons from Recent African Elections',
    author: 'Fatima Hassan',
    date: 'December 5, 2024',
    readTime: '7 min read',
    image:
      'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: 'Recent elections across Africa have demonstrated the profound impact of social media on democratic processes, revealing both its potential to enhance civic participation and its risks for spreading disinformation.',
      },
      { type: 'heading', text: 'The Double-Edged Sword' },
      {
        type: 'paragraph',
        text: 'Social media platforms have democratized political discourse, allowing ordinary citizens to engage directly with candidates and share information rapidly. However, these same platforms have been weaponized to spread false information and manipulate voter sentiment.',
      },
      { type: 'heading', text: 'Case Studies' },
      {
        type: 'paragraph',
        text: 'Elections in Kenya, Nigeria, and South Africa over the past two years have shown how coordinated disinformation campaigns can undermine trust in electoral processes and fuel social divisions.',
      },
    ],
  },
  'the-future-of-work-in-africa-balancing-automation-and-employment': {
    title: 'The Future of Work in Africa: Balancing Automation and Employment',
    author: 'Joseph Banda',
    date: 'November 28, 2024',
    readTime: '9 min read',
    image:
      'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: "As automation and AI technologies advance globally, African nations face critical decisions about how to balance technological progress with employment needs in a continent with the world's youngest and fastest-growing population.",
      },
      { type: 'heading', text: 'The Employment Challenge' },
      {
        type: 'paragraph',
        text: 'Africa needs to create millions of jobs annually to absorb new entrants into the workforce. Automation threatens to disrupt traditional employment sectors before alternative opportunities can be developed.',
      },
      { type: 'heading', text: 'Opportunities in the Digital Economy' },
      {
        type: 'paragraph',
        text: 'However, the digital economy also presents unprecedented opportunities for African workers to participate in global markets, provided they have access to education, training, and infrastructure.',
      },
    ],
  },
  'building-trustworthy-ai-systems-for-public-services-in-africa': {
    title: 'Building Trustworthy AI Systems for Public Services in Africa',
    author: 'Dr. Thabo Makena',
    date: 'November 20, 2024',
    readTime: '10 min read',
    image:
      'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: 'As African governments increasingly turn to AI to improve public service delivery, ensuring these systems are trustworthy, transparent, and accountable becomes paramount.',
      },
      { type: 'heading', text: 'Defining Trustworthy AI' },
      {
        type: 'paragraph',
        text: 'Trustworthy AI systems must be accurate, fair, secure, and respectful of privacy and human rights. They should be developed through participatory processes that include diverse stakeholders.',
      },
      { type: 'heading', text: 'Implementation Challenges' },
      {
        type: 'paragraph',
        text: 'Many African governments lack the technical capacity and regulatory frameworks needed to properly evaluate and oversee AI systems. This creates risks of deploying systems that may be biased, insecure, or inappropriate for local contexts.',
      },
    ],
  },
  'data-rights-as-human-rights-a-framework-for-africa': {
    title: 'Data Rights as Human Rights: A Framework for Africa',
    author: 'Aisha Kamara',
    date: 'November 15, 2024',
    readTime: '8 min read',
    image:
      'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1200&h=600&fit=crop',
    content: [
      {
        type: 'paragraph',
        text: 'As personal data becomes increasingly central to economic and social life, there is growing recognition that data rights should be understood as fundamental human rights that require legal protection.',
      },
      { type: 'heading', text: 'Beyond Privacy' },
      {
        type: 'paragraph',
        text: "Data rights encompass more than just privacy. They include rights to access one's own data, to correct inaccuracies, to understand how data is used, and to benefit from the value created by one's data.",
      },
      { type: 'heading', text: 'An African Framework' },
      {
        type: 'paragraph',
        text: 'African nations should develop data rights frameworks that reflect African values of community, solidarity, and collective well-being, rather than purely individualistic Western models.',
      },
    ],
  },
};

export function ArticleDetails() {
  const { slug } = useParams();
  const article = articles[slug];

  if (!article) {
    return (
      <div className="min-h-screen bg-white flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl font-serif text-gray-800 mb-4">
            Article Not Found
          </h1>
          <Link to="/blog" className="text-[#00CAFF] hover:underline">
            Return to Blog
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      {/* Hero Image */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.6 }}
        className="w-full h-[50vh] relative overflow-hidden"
      >
        <img
          src={article.image || '/placeholder.svg'}
          alt={article.title}
          className="w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
      </motion.div>

      {/* Article Content */}
      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Back Button */}
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.5 }}
        >
          <Link
            to="/blog"
            className="inline-flex items-center gap-2 uppercase text-gray-600 hover:text-[#00CAFF] transition-colors mb-8 text-xs"
          >
            <FaArrowLeft className="text-xs" />
            <span>Back to Blog</span>
          </Link>
        </motion.div>

        {/* Article Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          <h1 className="text-4xl md:text-5xl font-serif text-gray-900 mb-6 leading-tight">
            {article.title}
          </h1>

          {/* Article Meta */}
          <div className="flex flex-wrap items-center gap-6 text-sm text-gray-600 mb-8 pb-8 border-b border-gray-200">
            <div className="flex items-center gap-2">
              <FaUser className="text-[#00CAFF]" />
              <span>{article.author}</span>
            </div>
            <div className="flex items-center gap-2">
              <FaCalendar className="text-[#00CAFF]" />
              <span>{article.date}</span>
            </div>
            <div className="flex items-center gap-2">
              <FaClock className="text-[#00CAFF]" />
              <span>{article.readTime}</span>
            </div>
          </div>
        </motion.div>

        {/* Article Body */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.4 }}
          className="prose prose-lg max-w-none"
        >
          {article.content.map((block, index) => {
            if (block.type === 'heading') {
              return (
                <h2
                  key={index}
                  className="text-2xl font-serif text-gray-900 mt-8 mb-4"
                >
                  {block.text}
                </h2>
              );
            }
            if (block.type === 'paragraph') {
              return (
                <p key={index} className="text-gray-700 leading-relaxed mb-6">
                  {block.text}
                </p>
              );
            }
            return null;
          })}
        </motion.div>

        {/* Related Articles / Call to Action */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-12 pt-8 border-t border-gray-200"
        >
          <div className="bg-gradient-to-r from-[#0F1662] to-[#4065FF] rounded-t-md rounded-b-2xl p-8 text-white text-center">
            <h3 className="text-2xl font-serif mb-4">Stay Informed</h3>
            <p className="mb-6 text-white/90">
              Subscribe to our newsletter for the latest insights on AI,
              democracy, and digital rights in Africa.
            </p>
            <button className="bg-[#00CAFF] text-[#0F1662] px-8 py-3 hover:bg-white transition-colors">
              Subscribe Now
            </button>
          </div>
        </motion.div>
      </div>
    </div>
  );
}

export default ArticleDetails;
